### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by andybondar** [oionis/docker-kuber#1]
## Removing unnecessary files and folders from the repository
The following doesn't have to be sent to the repo:
* `build` folder
* `gradle` folder
* `.gradle` folder
* `gradlew` and `gradlew.bat` files
* `.idea` folder

Add them to `.gitignore` file. Maybe with exception to the `gradlew` and/or `gradlew.bat`, as we discussed.

## Containerizing the App
We can break down this process into 2 parts:
* Creating a `.jar` archive using Gradle/Gradle Wrapper (or whatever builder you like)
* Building a runtime container

If you write in Java lot, it is expected that you have JDK, Gradle, Gradle Wrapper and other stuff like that installed on your computer. However, if you need to integrate the Java App packages building workflow into an existing CI pipeline, where the other Apps, written in Go, Python, Ruby, JavaScript, etc., are also built and packaged, it seems to be not rational to install and maintain all the dependencies there. Instead, you might want you use a **multi-stage building** definition in a `Dockerfile`, which would look like this in your case:

* move your Dockerfile to the root folder of the repo: `mv info-service/Dockerfile .`
* modify it like the following:
```Dockerfile
# Build stage
FROM alpine:3.14.3 AS builder

RUN apk --no-cache add openjdk11 gradle
RUN mkdir /app
COPY info-service/ /app/
WORKDIR /app
RUN gradle wrapper && ./gradlew clean && ./gradlew build

# Run stage
FROM alpine:3.14.3

RUN apk --no-cache add openjdk11-jre
RUN mkdir /opt/info-service
COPY --from=builder /app/build/libs/*.jar /opt/info-service/info-service.jar

ENTRYPOINT ["java", "-jar", "/opt/info-service/info-service.jar"]
EXPOSE 8076
```
>**Note:** if you already have the *gradlew* executable(s) in your app code repo, you just don't need that **gradle wrapper** installation in the **RUN** instaruction.

Now, all you need to do is:
* Running the `docker build`
* Pushing the image to a container registry
meaning - the `docker engine` is the only software that you need in your CI environment to build a container image containing any runtime software you need.

Also, you need to figure out how to inject the container registry credentials into your CI pipeline, so you can push the image you built.

### Database Deployment
DB Server requires a persistent storage, which you decided to provide using the Kubernetes Node's local file system. There are a few issues with that:

While it's okay using `hostPath` for tutorials, hands-on labs and such, it’s strongly not recommended for the production-like environments. The reasons are basically the following:
* It poses a security threat. Read more on that in the Kubernetes official documentation [here](https://kubernetes.io/docs/concepts/storage/volumes/)
* A Kubernetes Node is in fact an ephemeral entity. Not as ephemeral as a Pod, but still, it can be deleted during a cluster autoscaling,  a node pool upgrade, etc. You cannot expect that the data stored on a Node's local file system will be persistent, you can lose at any time.

Also, I tried to deploy the Postgres DB to a GKE Cluster using your manifest, and it failed for the following reason:

Here is the PV and PVC configuration in your manifest:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
    project: docker-kubernetes
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
    project: docker-kubernetes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
```

While the PV was created successfully:
```
$ kubectl get pv
NAME          CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
postgres-pv   4Gi        RWX            Retain           Available           manual                  40s
```

the PVC's stuck in `Pending` state:
```
$ kubectl get pvc
NAME           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
postgres-pvc   Pending                                      standard       48s
```

and here is the reason:
```
Events:
  Type     Reason              Age                   From                         Message
  ----     ------              ----                  ----                         -------
  Warning  ProvisioningFailed  32s (x11 over 8m43s)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported
```

which is because a PVC uses the default `StorageClass` to provision the `PersistentVolume` it claims, unless you explicitly specify a `StorageClass` to use (**manual** in your case) and an already existing `PersistentVolume` (**postgres-pv** in your case) to claim:

<details>
<summary>GKE default StorageClass:</summary>

```
$ kubectl get sc
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
premium-rwo          pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   21m
standard (default)   kubernetes.io/gce-pd    Delete          Immediate              true                   21m
standard-rwo         pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   21m
```

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: standard
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

</details>

The default `standard` StorageClass provisions a Google Cloud Platform's resource called the `Google Cloud Engine Persistent Disk` as a block storage device for the PV it creates (take a look at the `type: pd-standard` parameter in the `StorageClass` manifest). The `gce-pd` only supports `ReadWriteOnce` mode.

As the result, the `Pod` has also got stuck in the `Pending` state because it's unable to mount the volume.

>**Note:** More on Kubernetes Storage Classes:
>https://kubernetes.io/docs/concepts/storage/storage-classes/

Now, if you want to use Node's local file system as a storage, here is a working configuration example for PV and PVC (please pay attention to the fact that the `storageClassName` and `volumeName` are explicitly specified in the PVC configuration):

<details>
<summary>PV and PVC configuration example, hostPath is used:</summary>

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
    project: docker-kubernetes
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
    project: docker-kubernetes
spec:
  storageClassName: manual
  volumeName: postgres-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
```
</details>

>**Note:** the **/mnt/data**  folder must be created in the Node prior to running the deployment.

If you can go with GCE PD as a block storage device for the PostgreSQL Server, which is what I recommend, here is a configuration example for that (the only access mode in the `accessModes` list is `ReadWriteOnce`, PV manifest is not required):

<details>
<summary>PV and PVC configuration example, GKE default StorageClass is used:</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
    project: docker-kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

</details>

### App Deployment
In order to expose App's HTTP endpoint to the Internet, `type: LoadBalancer` must be used in the Server's specification:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: info-service
  labels:
    app: info-service
    project: docker-kubernetes
spec:
  selector:
    app: info-service
  ports:
    - port: 8076
      targetPort: 8076
  type: LoadBalancer
```

The external IP address has been assigned, and now we can access the App's HTTP endpoint from any host in the Internet:
```
$ kubectl get svc | grep info-service
info-service   LoadBalancer   10.76.0.6     34.134.211.165   8076:32082/TCP   110s

curl -I http://34.134.211.165:8076
HTTP/1.1 200 
Content-Type: text/html;charset=UTF-8
Content-Language: en-US
Content-Length: 524
Date: Thu, 25 Nov 2021 19:13:21 GMT
```

>**Note: it's not working anymore because I destroyed the deployment :)**

### Namespaces
It is strongly recommended to avoid placing any user's payload to the `default` namespace. It is much better to create a dedicated one for that, with a meaningful name. The `info-service` would absolutely do for this case.
